---
- name: Manage Komodo Periphery Service
  hosts: komodo
  roles:
    - role: bpbradley.komodo
      # Default action / version. Can be overriden on command line with -e
      komodo_action: "install"
      komodo_version: "v1.18.3"
