---
- name: Compatibility checks
  vars:
    deprecated_vars:
      - { old: 'periphery_port', new: 'komodo_periphery_port' }
      - { old: 'root_dir', new: 'komodo_root_directory' }
      - { old: 'repo_dir', new: 'komodo_repo_dir' }
      - { old: 'stack_dir', new: 'komodo_stack_dir' }
      - { old: 'build_dir', new: 'komodo_build_dir' }
      - { old: 'stacks_polling_rate', new: 'komodo_stats_polling_rate' }
      - { old: 'ssl_enabled', new: 'komodo_ssl_enabled' }
      - { old: 'logging_level', new: 'komodo_logging_level' }
      - { old: 'logging_stdio', new: 'komodo_logging_stdio' }
      - { old: 'logging_opentelemetry_service_name', new: 'komodo_logging_opentelemetry_service_name' }
      - { old: 'komodo_core_url', new: 'komodo_core_http_address' }
    deprecated_configs:
      - { old: ['passkey', 'komodo_passkeys', 'server_passkey', 'generate_server_passkey'], 
          note: 'Passkey authentication is deprecated. When able, remove these variables and switch to Outbound Connection (`komodo_server_enabled=false`) or use `komodo_core_public_key` with Inbound Connection.' }
  block:
    - name: Cache defined var names on this host
      ansible.builtin.set_fact:
        _all_var_keys: "{{ hostvars[inventory_hostname] | dict2items | map(attribute='key') | list }}"
      changed_when: false

    - name: Find deprecated vars present
      ansible.builtin.set_fact:
        _deprecated_vars: >-
          {{
            deprecated_vars
            | selectattr('old', 'in', _all_var_keys)
            | list
          }}
      changed_when: false

    - name: Find deprecated configs present
      ansible.builtin.set_fact:
        _deprecated_configs: >-
          {{
            (_deprecated_configs | default([]))
            + [ item | combine({'hits': (item.old | intersect(_all_var_keys))}) ]
          }}
      when: (item.old | intersect(_all_var_keys)) | length > 0
      loop: "{{ deprecated_configs }}"
      loop_control:
        label: "{{ (item.old | intersect(_all_var_keys)) | join(', ') | default('none') }}"
      changed_when: false

    - name: Variable Deprecation Warnings
      warn:
        msg: "[DEPRECATION] {{ item.old }} is deprecated. Use {{ item.new }}."
      when: _deprecated_vars | length > 0
      loop: "{{ _deprecated_vars }}"
      loop_control:
        label: "{{ item.old }} -> {{ item.new }}"
      changed_when: false
  
    - name: Configuration Deprecation Warnings
      when: _deprecated_configs | default([]) | length > 0
      warn:
        msg: "[DEPRECATION] vars={{ item.hits | join(', ') }} defined: {{ item.note }}"
      loop: "{{ _deprecated_configs }}"
      loop_control:
        label: "{{ item.hits | join(' | ') }} is Deprecated!"
      changed_when: false
