---
- name: Configure User
  block:
    - name: Ensure Komodo group exists
      become: true
      ansible.builtin.group:
        name: "{{ komodo_group }}"
      when: not komodo_group_exists | bool

    - name: Ensure Komodo user exists
      become: true
      ansible.builtin.user:
        name: "{{ komodo_user }}"
        group: "{{ komodo_group }}"
        shell: /usr/sbin/nologin
        create_home: true
        home: "{{ komodo_home }}"
      when: not komodo_user_exists | bool

    - name: Refresh Komodo user context
      ansible.builtin.import_tasks: _user_ctx.yml

    - name: Create Ansible temp directory for komodo user
      become: true
      ansible.builtin.file:
        path: "{{ komodo_home }}/.ansible/tmp"
        state: directory
        owner: "{{ komodo_user }}"
        group: "{{ komodo_group }}"
        mode: "0700"

    - name: Add Komodo user to the docker group
      become: true
      ansible.builtin.user:
        name: "{{ komodo_user }}"
        groups: docker
        append: true

    - name: Enable lingering for Komodo user
      ansible.builtin.command: loginctl enable-linger {{ komodo_user }}
      when: komodo_service_scope == "user"
      become: true
      changed_when: false
