---

- name: Compatibility checks
  vars:
    deprecated_vars:
      - { old: 'passkey', new: 'komodo_passkeys' }
      - { old: 'periphery_port', new: 'komodo_periphery_port' }
      - { old: 'root_dir', new: 'komodo_root_directory' }
      - { old: 'repo_dir', new: 'komodo_repo_dir' }
      - { old: 'stack_dir', new: 'komodo_stack_dir' }
      - { old: 'build_dir', new: 'komodo_build_dir' }
      - { old: 'stacks_polling_rate', new: 'komodo_stats_polling_rate' }
      - { old: 'ssl_enabled', new: 'komodo_ssl_enabled' }
      - { old: 'logging_level', new: 'komodo_logging_level' }
      - { old: 'logging_stdio', new: 'komodo_logging_stdio' }
      - { old: 'logging_opentelemetry_service_name', new: 'komodo_logging_opentelemetry_service_name' }
  block:
    - name: Find defined deprecated variables
      ansible.builtin.set_fact:
        defined_deprecated_vars: >-
          {{ deprecated_vars | selectattr('old', 'in', hostvars[inventory_hostname] | list) | list }}

    - name: Warn on deprecated variables
      ansible.builtin.fail:
        msg: "[DEPRECATION] '{{ item.old }}' is deprecated. Use '{{ item.new }}'."
      loop: "{{ defined_deprecated_vars }}"
      ignore_errors: true # noqa ignore-errors
      when: defined_deprecated_vars | length > 0
      changed_when: false

- name: Ensure ACL package exists for switching to unprivileged user
  ansible.builtin.package:
    name: acl
    state: present
  become: true

- name: Build Komodo user context
  ansible.builtin.import_tasks: _user_ctx.yml

- name: Setup Komodo User
  ansible.builtin.include_tasks: setup_user.yml
  when: komodo_action in ["install","update"]

- name: Create Ansible temp directory for komodo user
  become: true
  ansible.builtin.file:
    path: "{{ komodo_home }}/.ansible/tmp"
    state: directory
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"
    mode: "0700"
  when: komodo_user_exists | bool

- name: Update Komodo Periphery Agent
  ansible.builtin.include_tasks: update.yml
  when: komodo_action in ["install","update"]

- name: Komodo server update tasks
  ansible.builtin.include_tasks: manage_server.yml
  when: komodo_action in ["install","update"]

- name: Periphery uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: komodo_action == "uninstall"
