---
- name: Ensure ACL package exists for switching to unprivileged user
  ansible.builtin.package:
    name: acl
    state: present
  become: true

- name: Build Komodo user context
  ansible.builtin.import_tasks: _user_ctx.yml

- name: Update Komodo Periphery
  ansible.builtin.include_tasks: update.yml
  when: komodo_action in ["install","update"]

- name: Periphery uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: komodo_action == "uninstall"

- name: Compatibility checks
  ansible.builtin.include_tasks: _compat.yml
  when: allow_komodo_deprecation_checks | default(true) | bool
