---
- name: Fail if unsupported architecture
  ansible.builtin.fail:
    msg: "Unsupported architecture: {{ ansible_facts.architecture }}. Supported architectures are x86_64 and aarch64."
  when: ansible_facts.architecture not in ['x86_64', 'aarch64']

- name: Setup Komodo user
  ansible.builtin.include_tasks: setup_user.yml

- name: Resolve Komodo version
  block:
    - name: Handle automatic versioning with core
      when: komodo_version | lower == "core"
      block:
        - name: Try /version endpoint
          failed_when: false
          changed_when: false
          check_mode: false
          delegate_to: "{{ komodo_api_delegate_to }}"
          become: false
          run_once: true
          ansible.builtin.uri:
            url: "{{ komodo_core_http_address | trim('/') }}/version"
            method: GET
            status_code: 200
            return_content: true
            timeout: 15
          register: _core_version

        - name: Query Core API to get Komodo version
          when: (_core_version.status | default(0)) != 200
          changed_when: false
          check_mode: false
          delegate_to: "{{ komodo_api_delegate_to }}"
          become: false
          run_once: true
          ansible.builtin.uri:
            url: "{{ komodo_core_http_address | trim('/') }}/read"
            method: POST
            body_format: json
            headers:
              Content-Type: application/json
              X-Api-Key: "{{ komodo_core_api_key }}"
              X-Api-Secret: "{{ komodo_core_api_secret }}"
            body:
              type: GetVersion
              params: {}
            status_code: 200
            return_content: true
            timeout: 15
          register: _api_core_version

        - name: Set Komodo version to Komodo Core response
          ansible.builtin.set_fact:
            _komodo_version: >-
              {{
                (
                  _core_version.content
                  if (_core_version.status | default(0)) == 200
                  else (_api_core_version.json.version | default(''))
                )
                | string | trim | regex_replace('^v','')
              }}
          changed_when: false

    - name: Handle automatic versioning set to latest
      when: komodo_version | lower == "latest"
      block:
        - name: Query GitHub for the latest Komodo release
          check_mode: false
          changed_when: false
          delegate_to: "{{ komodo_api_delegate_to }}"
          become: false
          run_once: true
          ansible.builtin.uri:
            url: "https://api.github.com/repos/moghtech/komodo/releases/latest"
            headers:
              Accept: application/vnd.github+json
            return_content: true
            status_code: 200
            timeout: 15
          register: _gh_release

        - name: Set Komodo version to latest GitHub tag
          ansible.builtin.set_fact:
            _komodo_version: "{{ _gh_release.json.tag_name | regex_replace('^v', '') }}"
          changed_when: false

    - name: Determine Komodo version
      when: _komodo_version is not defined
      ansible.builtin.set_fact:
        _komodo_version: "{{ komodo_version | regex_replace('^v', '') }}"

    - name: Display Komodo version
      ansible.builtin.debug:
        msg: "Using Komodo version: {{ _komodo_version }}"

- name: Check currently installed binary version
  ansible.builtin.command: "{{ komodo_bin_path }} --version"
  register: _current_binary_state
  become: true
  failed_when: false
  changed_when: false
  check_mode: false

- name: Parse installed version
  ansible.builtin.set_fact:
    _installed_version: >-
      {{
        (_current_binary_state.stdout | split | last | regex_replace('^v', ''))
        if (
          _current_binary_state.rc == 0 and
          _current_binary_state.stdout | default('') | length > 0
        )
        else ''
      }}

- name: Display version information
  ansible.builtin.debug:
    msg: "Current: {{ _installed_version if _installed_version | length > 0 else 'Unknown' }} | Target: {{ _komodo_version }}"

- name: Determine if binary update is required
  ansible.builtin.set_fact:
    _periphery_binary_needs_update: "{{ _installed_version != _komodo_version }}"

- name: Select Komodo binary
  vars:
    _komodo_bin_x86: "periphery-x86_64"
    _komodo_bin_x86_legacy: "periphery"
    _komodo_bin_aarch64: "periphery-aarch64"
  ansible.builtin.set_fact:
    binary_name: >-
      {%- if komodo_bin | length > 0 -%}
        {{ komodo_bin }}
      {%- elif ansible_facts.architecture == 'aarch64' -%}
        {{ _komodo_bin_aarch64 }}
      {%- else -%} {# x86_64 #}{%- if _komodo_version is version('1.16.12', '>=') -%}
          {{ _komodo_bin_x86 }}
      {%- else -%}
          {{ _komodo_bin_x86_legacy }}
      {%- endif -%} {%- endif -%}

- name: Generate a random passkey
  when:
    - enable_server_management | bool | default(false)
    - generate_server_passkey | bool | default(false)
    - server_passkey is not defined or (server_passkey | string | trim | length == 0)
    - _komodo_version is version('2.0.0', '<') or (_komodo_version is version('2.0.0', '>=') and (komodo_server_enabled | bool))
  ansible.builtin.set_fact:
    server_passkey: >-
      {{
        lookup('password',
        '/dev/null length=32 chars=ascii_letters,digits')
      }}

- name: Ensure binary directory exists
  become: true
  ansible.builtin.file:
    path: "{{ komodo_bin_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ komodo_user if komodo_bin_dir.startswith(komodo_home) else omit }}"
    group: "{{ komodo_group if komodo_bin_dir.startswith(komodo_home) else omit }}"

- name: Ensure necessary directories
  become: true
  ignore_errors: "{{ ansible_check_mode and not komodo_user_exists }}" # noqa ignore-errors
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"
    mode: "0750"
  loop:
    - "{{ komodo_config_dir }}"
    - "{{ komodo_root_directory }}"
    - "{{ komodo_root_directory }}/keys"
  when: item != (komodo_root_directory ~ '/keys') or (_komodo_version is version('2.0.0','>='))

- name: Manage Komodo Core auth keys
  when: _komodo_version is version('2.0.0','>=')
  vars:
    _normalized_core_keys: >-
      {{
        [komodo_core_public_key] | default([], true) | flatten
        | map('string') | map('trim') | reject('equalto','') | unique | list
      }}
  block:
    - name: Materialize keys to files
      when: allow_write_keys_to_files | bool
      block:
        - name: Handle Core public key files
          when: (_normalized_core_keys | length) > 0
          block:
            - name: Write Core public key files
              become: true
              register: _core_pub_keys_written
              no_log: true
              ansible.builtin.template:
                src: core.pub.j2
                dest: "{{ komodo_root_directory }}/keys/core.{{ idx + 1 }}.pub"
                owner: "{{ komodo_user }}"
                group: "{{ komodo_group }}"
                mode: "0640"
                force: "{{ allow_overwrite_key_files | bool }}"
              vars:
                _raw_core_pub_key: "{{ item }}"
              loop: "{{ _normalized_core_keys }}"
              loop_control:
                index_var: idx
              when: item is not match('^file:')

            - name: Build Core public key references
              ansible.builtin.set_fact:
                _core_public_keys: >-
                  {{
                    _core_public_keys | default([])
                    + [
                        (
                          'file:' ~ komodo_root_directory ~ '/keys/core.' ~ (idx + 1) ~ '.pub'
                        ) if not (item is match('^file:')) else item
                      ]
                  }}
              loop: "{{ _normalized_core_keys }}"
              loop_control:
                index_var: idx
                label: "pubkey[{{ idx }}] => {{ komodo_root_directory }}/keys/core.{{ idx + 1 }}.pub"

        - name: Handle private key file
          when:
            - komodo_private_key | string | trim | length > 0
            - not (komodo_private_key | string | trim) is match('^file:')
          block:
            - name: Write private key file
              become: true
              no_log: true
              register: _periphery_priv_key_written
              ansible.builtin.template:
                src: periphery.key.j2
                dest: "{{ komodo_root_directory }}/keys/periphery.key"
                owner: "{{ komodo_user }}"
                group: "{{ komodo_group }}"
                mode: "0600"
                force: "{{ allow_overwrite_key_files | bool }}"
              vars:
                _raw_komodo_private_key: "{{ komodo_private_key | string | trim }}"

            - name: Set private key reference
              ansible.builtin.set_fact:
                _periphery_private_key: "file:{{ komodo_root_directory }}/keys/periphery.key"

    - name: Ensure key references
      ansible.builtin.set_fact:
        _core_public_keys: "{{ _core_public_keys | default(_normalized_core_keys) }}"
        _periphery_private_key: "{{ _periphery_private_key | default(komodo_private_key) }}"

- name: Stop periphery service
  when: _periphery_binary_needs_update | bool
  become: true
  become_user: "{{ systemd_ctx[komodo_service_scope].become_user }}"
  environment: "{{ systemd_ctx[komodo_service_scope].environment | default({}) }}"
  ignore_errors: "{{ ansible_check_mode and not komodo_user_exists }}" # noqa ignore-errors
  ansible.builtin.systemd:
    name: periphery
    state: stopped
    scope: "{{ systemd_ctx[komodo_service_scope].scope }}"
  failed_when: false

- name: Remove old binaries
  when: _periphery_binary_needs_update | bool
  ignore_errors: "{{ ansible_check_mode and not komodo_user_exists }}" # noqa ignore-errors
  become: true
  ansible.builtin.file:
    path: "{{ komodo_bin_path }}"
    state: absent

- name: Download Komodo Periphery binary
  when: _periphery_binary_needs_update | bool
  become: true
  vars:
    _download_sources:
      github: "https://github.com/moghtech/komodo/releases/download/v{{ _komodo_version }}"
      forge: "https://forge.mogh.tech/api/packages/komodo/generic/periphery/{{ _komodo_version }}"
    _download_url: "{{ _download_sources[komodo_download_source] }}"
  ignore_errors: "{{ ansible_check_mode and not komodo_user_exists }}" # noqa ignore-errors
  ansible.builtin.get_url:
    url: "{{ _download_url }}/{{ binary_name }}"
    dest: "{{ komodo_bin_path }}"
    mode: "0755"
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"
    force: true

- name: Ensure user systemd dirs exist
  become: true
  loop:
    - "{{ komodo_home }}/.config"
    - "{{ komodo_home }}/.config/systemd"
    - "{{ komodo_home }}/.config/systemd/user"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"
    mode: "0750"
  when:
    - komodo_service_scope == 'user'

- name: Deploy configuration file
  register: _config_file_written
  become: true
  ignore_errors: "{{ ansible_check_mode and not komodo_user_exists }}" # noqa ignore-errors
  ansible.builtin.template:
    src: "{{ komodo_config_file_template }}"
    dest: "{{ komodo_config_path }}"
    mode: "0640"
    owner: "{{ komodo_user }}"
    group: "{{ komodo_group }}"

- name: Install systemd unit file
  register: _service_unit_written
  ignore_errors: "{{ ansible_check_mode and not komodo_user_exists }}" # noqa ignore-errors
  become: true
  vars:
    _system_scope: "{{ (komodo_service_scope | default('user')) == 'system' }}"
    _service_dir: "{{ '/etc/systemd/system' if _system_scope else (komodo_home ~ '/.config/systemd/user') }}"
  ansible.builtin.template:
    src: "{{ komodo_service_file_template }}"
    dest: "{{ _service_dir }}/periphery.service"
    owner: "{{ 'root' if _system_scope else komodo_user }}"
    group: "{{ 'root' if _system_scope else komodo_group }}"
    mode: "0644"

- name: Determine restart requirement
  ansible.builtin.set_fact:
    _restart_required: >-
      {{
        (_periphery_binary_needs_update | bool) or
        (_config_file_written.changed | bool) or
        (_service_unit_written.changed | bool) or
        ((_core_pub_keys_written | default({})).changed | default(false) | bool) or
        ((_periphery_priv_key_written | default({})).changed | default(false) | bool)
      }}

- name: Ensure periphery service is running
  become: true
  become_user: "{{ systemd_ctx[komodo_service_scope].become_user }}"
  environment: "{{ systemd_ctx[komodo_service_scope].environment | default({}) }}"
  ignore_errors: "{{ ansible_check_mode and not komodo_user_exists }}" # noqa ignore-errors
  ansible.builtin.systemd:
    name: periphery
    enabled: true
    state: "{{ _restart_required | ternary('restarted', 'started') }}"
    scope: "{{ systemd_ctx[komodo_service_scope].scope }}"
    daemon_reload: "{{ _service_unit_written.changed | default(false) }}"

- name: Komodo server management tasks
  ansible.builtin.include_tasks: manage_server.yml
  when:
    - enable_server_management | bool
    - _komodo_version is version('2.0.0', '<') or (_komodo_version is version('2.0.0', '>=') and (komodo_server_enabled | bool))
