all:
  hosts:
    komodo_host1:
      ansible_host: 10.1.10.4
    komodo_host2:
      ansible_host: 10.1.10.5
    komodo_host3:
      ansible_host: 10.1.10.6
    localhost:
      ansible_host: localhost
      connection: local
  children:
    komodo:
      vars:
        # These variables are only needed if using the server management feature
        # This feature allows the role to automatically register and update
        # servers in komodo core in addition to deploying periphery
        komodo_core_url: "https://komodo.example.com"
        # Encrypt these with vault!
        komodo_core_api_key: "some_api_key" 
        komodo_core_api_secret: "some_api_secret" 
        # Default to allowing server management feature
        enable_server_management: true
      children:
        core:
          hosts:
            komodo_host1:
              # This host overrides the default behavior and doesnt allow server
              # management
              enable_server_management: false
              # Can be an internal docker IP for example if on the same host
              komodo_allowed_ips:
                - "172.20.0.101"
              komodo_bind_ip: 0.0.0.0
        periphery:
          hosts:
            komodo_host2:
              # This host will allow a new key to be generated and rotated
              # with every install and update
              generate_server_passkey: true
              komodo_allowed_ips:
                - "::ffff:10.1.10.4"
            komodo_host3:
              # This host will specify its own specific server passkey
              # This passkey can be encrypted with vault!
              server_passkey: some-secret-passkey
              komodo_allowed_ips:
                - "10.1.10.4"
              komodo_bind_ip: 0.0.0.0
