all:
  # Here you can have your typical inventory configurations.
  # Add additonal vars: section for ssh keyfiles, etc.
  hosts:
    # Important: for best automation, name your hosts in your inventory
    # the exact same way that they are named in komodo.
    # This way, komodo can be "aware" of your ansible hosts automatically.
    # and automation features will work seamlessly.
    internal_server:
      ansible_host: 10.1.10.4
    external_server:
      ansible_host: 10.1.10.5
    test_server:
      ansible_host: 10.1.10.6
  vars:
    ansible_user: actual_user_to_run_playbook_as
    # This role needs elevated privileges for some tasks.
    # remember to encrypt ansible_become_pass with vault.
    ansible_become_pass: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            65353234373130353539663661376563613539303866643963363830376661316638333139343366
            3563656637303235373336336131346338336634653232300a313736396336316330666237653237
            64613231323433373637313462633863613732653136366462313134393938623136326633346166
            3834333462333162310a313037306336613061313733363862633437376133316234326431633131
            35386565333538623231643433396334323132616438353839663534373030393266
    # You will need to mount any ssh keys into the container,
    # with the correct permissions for the user the container is running as
    ansible_ssh_private_key_file: /root/.ssh/id_ed25519 # i.e. (/path/to/ssh/key/in/container)
    # Because all nodes are outbound, we can define the core address as shared.
    komodo_core_address: "wss://komodo.example.com"
    komodo_server_enabled: false
  children:
    komodo:
      vars:
        # I like to "inform" each server what UID/GID it is running as
        # which is useful when running containers as the komodo user.
        # The role will also populate the UID/GID env variables in the
        # systemd service file for you, but this is just a convenience.
        komodo_agent_secrets:
          - name: "KOMODO_UID"
            value: "{{ ansible_facts.getent_passwd[komodo_user].1 }}"
          - name: "KOMODO_GID"
            value: "{{ ansible_facts.getent_passwd[komodo_user].2 }}"
      children:
        # It isn't necessary to split the inventory up into core / periphery,
        # but it is useful for organization and I personally have other roles
        # which only target core or periphery exclusively.
        core:
          hosts:
            internal_server:
              # Maybe you want to reach core with a different address on some servers.
              # You can override the group var here.
              komodo_core_address: "wss://komodo.example.com" 
        periphery:
          hosts:
            external_server:
              # Add any additional secrets you want here, This will override
              # the group vars.
              komodo_agent_secrets:
                - name: "KOMODO_UID"
                  value: "{{ ansible_facts.getent_passwd[komodo_user].1 }}"
                - name: "KOMODO_GID"
                  value: "{{ ansible_facts.getent_passwd[komodo_user].2 }}"
                - name: "SUPER_SECRET"
                  value: !vault |
                    $ANSIBLE_VAULT;1.1;AES256
                    66386439653762316464626437653766643665373063...
            test_server:
              # Not usually needed, but maybe you need to manually set a specific
              # private key for this server.
              komodo_private_key: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                62336466363161396537316566366466323266663536...
              # This would allow the role to overwrite existing key files
              # on this server, if they already exist.
              allow_overwrite_key_files: true
