name: Build Ansible EE
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_URI: ghcr.io/${{ github.repository_owner }}/ansible/komodo-ee

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ee-builder
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ansible-builder
        run: python -m pip install --upgrade pip ansible-builder==3.*

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          ansible-builder build \
          --container-runtime docker \
          --tag $IMAGE_URI:latest 

      - name: Push image
        run: docker push $IMAGE_URI:latest